export const categories = [
  { id: 'cat-1', name: 'Laptopy', slug: 'laptops' },
  { id: 'cat-2', name: 'Monitory', slug: 'monitors' },
  { id: 'cat-3', name: 'Gry', slug: 'games' },
  { id: 'cat-4', name: 'Smartfony', slug: 'smartphones' },
  { id: 'cat-5', name: 'Peryferia', slug: 'peripherals' },
];

export const products = [
  // --- Laptopy ---
  {
    id: 'prod-1',
    name: 'Lenovo IdeaPad 3 15"',
    slug: 'lenovo-ideapad-3-15',
    description: 'Laptop biurowy z Ryzen 5, 16 GB RAM i SSD 512 GB.',
    price: 2499.99,
    image: '/images/products/lenovo-ideapad-3-15.jpg',
    categoryId: 'cat-1',
    inStock: true,
    isNew: true,
  },
  {
    id: 'prod-2',
    name: 'ASUS ROG Strix G16',
    slug: 'asus-rog-strix-g16',
    description: 'Laptop gamingowy z RTX 4060 i ekranem 165 Hz.',
    price: 5999.0,
    image: '/images/products/asus-rog-strix-g16.jpg',
    categoryId: 'cat-1',
    inStock: true,
    isHit: true,
  },
  {
    id: 'prod-3',
    name: 'Dell Inspiron 14',
    slug: 'dell-inspiron-14',
    description: 'Lekki laptop do nauki i pracy zdalnej.',
    price: 3199.0,
    image: '/images/products/dell-inspiron-14.jpg',
    categoryId: 'cat-1',
    inStock: true,
    isPromo: true,
  },
  {
    id: 'prod-4',
    name: 'Apple MacBook Air M2',
    slug: 'apple-macbook-air-m2',
    description: 'Ultrabook z chipem M2, 8 GB RAM i SSD 256 GB.',
    price: 4999.0,
    image: '/images/products/apple-macbook-air-m2.jpg',
    categoryId: 'cat-1',
    inStock: true,
    isHit: true,
  },
  {
    id: 'prod-5',
    name: 'HP Pavilion 15',
    slug: 'hp-pavilion-15',
    description: 'Uniwersalny laptop do domu i biura z Intel Core i5.',
    price: 2799.0,
    image: '/images/products/hp-pavilion-15.jpg',
    categoryId: 'cat-1',
    inStock: true,
    isSale: true,
  },
  {
    id: 'prod-6',
    name: 'Acer Nitro 5',
    slug: 'acer-nitro-5',
    description: 'Laptop gamingowy z RTX 4050 i ekranem 144 Hz.',
    price: 4499.0,
    image: '/images/products/acer-nitro-5.jpg',
    categoryId: 'cat-1',
    inStock: true,
    isNew: true,
  },

  // --- Monitory ---
  {
    id: 'prod-7',
    name: 'Samsung Odyssey G5 27"',
    slug: 'samsung-odyssey-g5-27',
    description: 'Monitor zakrzywiony 1440p, 165 Hz, FreeSync.',
    price: 1299.0,
    image: '/images/products/samsung-odyssey-g5-27.jpg',
    categoryId: 'cat-2',
    inStock: true,
    isHit: true,
  },
  {
    id: 'prod-8',
    name: 'LG UltraGear 24"',
    slug: 'lg-ultragear-24',
    description: 'Monitor gamingowy Full HD 180 Hz.',
    price: 699.0,
    image: '/images/products/lg-ultragear-24.jpg',
    categoryId: 'cat-2',
    inStock: true,
    isSale: true,
  },
  {
    id: 'prod-9',
    name: 'Gigabyte M27Q',
    slug: 'gigabyte-m27q',
    description: 'Monitor 27" QHD z KVM i USB-C.',
    price: 1499.0,
    image: '/images/products/gigabyte-m27q.jpg',
    categoryId: 'cat-2',
    inStock: true,
    isNew: true,
  },
  {
    id: 'prod-10',
    name: 'Dell UltraSharp U2723QE',
    slug: 'dell-ultrasharp-u2723qe',
    description: 'Monitor biurowy 4K IPS z hubem USB-C.',
    price: 2499.0,
    image: '/images/products/dell-ultrasharp-u2723qe.jpg',
    categoryId: 'cat-2',
    inStock: true,
    isPromo: true,
  },
  {
    id: 'prod-11',
    name: 'BenQ GW2485TC',
    slug: 'benq-gw2485tc',
    description: 'Monitor 24" Full HD z regulacją wysokości i USB-C.',
    price: 899.0,
    image: '/images/products/benq-gw2485tc.jpg',
    categoryId: 'cat-2',
    inStock: true,
  },
  {
    id: 'prod-12',
    name: 'MSI Optix G27C4',
    slug: 'msi-optix-g27c4',
    description: 'Zakrzywiony monitor gamingowy 27" Full HD 165 Hz.',
    price: 999.0,
    image: '/images/products/msi-optix-g27c4.jpg',
    categoryId: 'cat-2',
    inStock: true,
    isSale: true,
  },

  // --- Gry ---
  {
    id: 'prod-13',
    name: 'Cyberpunk 2077',
    slug: 'cyberpunk-2077',
    description: 'RPG w otwartym świecie Night City.',
    price: 149.0,
    image: '/images/products/cyberpunk-2077.jpg',
    categoryId: 'cat-3',
    inStock: true,
    isSale: true,
  },
  {
    id: 'prod-14',
    name: 'Counter-Strike 2',
    slug: 'counter-strike-2',
    description: 'Klasyczny FPS — klucz cyfrowy.',
    price: 0,
    image: '/images/products/counter-strike-2.jpg',
    categoryId: 'cat-3',
    inStock: true,
  },
  {
    id: 'prod-15',
    name: 'Resident Evil 4 Remake',
    slug: 'resident-evil-4-remake',
    description: 'Horror akcji — remake kultowej gry.',
    price: 199.0,
    image: '/images/products/resident-evil-4-remake.jpg',
    categoryId: 'cat-3',
    inStock: true,
    isNew: true,
  },
  {
    id: 'prod-16',
    name: 'Elden Ring',
    slug: 'elden-ring',
    description: 'Epickie action RPG w otwartym świecie FromSoftware.',
    price: 229.0,
    image: '/images/products/elden-ring.jpg',
    categoryId: 'cat-3',
    inStock: true,
    isHit: true,
  },
  {
    id: 'prod-17',
    name: 'EA Sports FC 25',
    slug: 'ea-sports-fc-25',
    description: 'Najnowsza odsłona piłkarskiej serii EA Sports.',
    price: 249.0,
    image: '/images/products/ea-sports-fc-25.jpg',
    categoryId: 'cat-3',
    inStock: true,
    isPromo: true,
  },
  {
    id: 'prod-18',
    name: "Baldur's Gate 3",
    slug: 'baldurs-gate-3',
    description: 'Kultowe RPG oparte na zasadach Dungeons & Dragons.',
    price: 199.0,
    image: '/images/products/baldurs-gate-3.jpg',
    categoryId: 'cat-3',
    inStock: true,
    isNew: true,
  },

  // --- Smartfony ---
  {
    id: 'prod-19',
    name: 'Samsung Galaxy A55',
    slug: 'samsung-galaxy-a55',
    description: 'Smartfon mid-range z dobrym aparatem.',
    price: 1799.0,
    image: '/images/products/samsung-galaxy-a55.jpg',
    categoryId: 'cat-4',
    inStock: true,
    isPromo: true,
  },
  {
    id: 'prod-20',
    name: 'Xiaomi Redmi Note 13',
    slug: 'xiaomi-redmi-note-13',
    description: 'Smartfon w dobrej cenie do codziennego użytku.',
    price: 999.0,
    image: '/images/products/xiaomi-redmi-note-13.jpg',
    categoryId: 'cat-4',
    inStock: true,
    isSale: true,
  },
  {
    id: 'prod-21',
    name: 'Google Pixel 8a',
    slug: 'google-pixel-8a',
    description: 'Smartfon Google z czystym Androidem i świetnym aparatem AI.',
    price: 2199.0,
    image: '/images/products/google-pixel-8a.jpg',
    categoryId: 'cat-4',
    inStock: true,
    isNew: true,
  },
  {
    id: 'prod-22',
    name: 'Apple iPhone SE 2022',
    slug: 'apple-iphone-se-2022',
    description: 'Kompaktowy iPhone z chipem A15 i Touch ID.',
    price: 2499.0,
    image: '/images/products/apple-iphone-se-2022.jpg',
    categoryId: 'cat-4',
    inStock: true,
    isHit: true,
  },
  {
    id: 'prod-23',
    name: 'Motorola Edge 50 Fusion',
    slug: 'motorola-edge-50-fusion',
    description: 'Smartfon z jasnym ekranem pOLED i szybkim ładowaniem.',
    price: 1499.0,
    image: '/images/products/motorola-edge-50-fusion.jpg',
    categoryId: 'cat-4',
    inStock: true,
    isPromo: true,
  },
  {
    id: 'prod-24',
    name: 'Nothing Phone (2a)',
    slug: 'nothing-phone-2a',
    description: 'Smartfon z Glyph Interface i czystym Androidem.',
    price: 1699.0,
    image: '/images/products/nothing-phone-2a.jpg',
    categoryId: 'cat-4',
    inStock: true,
    isSale: true,
  },

  // --- Peryferia ---
  {
    id: 'prod-25',
    name: 'Logitech MX Keys',
    slug: 'logitech-mx-keys',
    description: 'Bezprzewodowa klawiatura biurowa z podświetleniem.',
    price: 449.0,
    image: '/images/products/logitech-mx-keys.jpg',
    categoryId: 'cat-5',
    inStock: true,
    isHit: true,
  },
  {
    id: 'prod-26',
    name: 'Razer DeathAdder V3',
    slug: 'razer-deathadder-v3',
    description: 'Ergonomiczna mysz gamingowa z sensorem Focus Pro 30K.',
    price: 299.0,
    image: '/images/products/razer-deathadder-v3.jpg',
    categoryId: 'cat-5',
    inStock: true,
    isNew: true,
  },
  {
    id: 'prod-27',
    name: 'HyperX Cloud III',
    slug: 'hyperx-cloud-iii',
    description: 'Słuchawki gamingowe z mikrofonem i dźwiękiem przestrzennym.',
    price: 399.0,
    image: '/images/products/hyperx-cloud-iii.jpg',
    categoryId: 'cat-5',
    inStock: true,
    isPromo: true,
  },
  {
    id: 'prod-28',
    name: 'Logitech C920s HD Pro',
    slug: 'logitech-c920s-hd-pro',
    description: 'Kamera internetowa Full HD do wideokonferencji.',
    price: 349.0,
    image: '/images/products/logitech-c920s-hd-pro.jpg',
    categoryId: 'cat-5',
    inStock: true,
  },
  {
    id: 'prod-29',
    name: 'Creative Pebble V3',
    slug: 'creative-pebble-v3',
    description: 'Kompaktowe głośniki USB-C z Bluetooth do biurka.',
    price: 199.0,
    image: '/images/products/creative-pebble-v3.jpg',
    categoryId: 'cat-5',
    inStock: true,
    isSale: true,
  },
  {
    id: 'prod-30',
    name: 'SteelSeries QcK Large',
    slug: 'steelseries-qck-large',
    description: 'Duża podkładka pod mysz o gładkiej powierzchni tekstylnej.',
    price: 79.0,
    image: '/images/products/steelseries-qck-large.jpg',
    categoryId: 'cat-5',
    inStock: true,
    isNew: true,
  },
];
